### ISSUE TITLE
feat(ac-realms): web admin portal

### ISSUE THREAD

**Issue by DarktideLegend** [DarktideLegend/escape-from-dereth#17]
**Description**

ac-realms needs a web admin portal for server admins. 

**Desired Solution**

* It should allow admins to dynamically add, remove, update the rulesets of realms as well as provide analytical information about the server.

**Comment by xAdvan** [comment]
you maybe able to use this as a base for this system.
Dereth forever and an online DB connected content editor that did everything live..

https://gitlab.com/DerethForever/ContentEditor

**Comment by xAdvan** [comment]
https://www.youtube.com/watch?v=UTPY7atvXOo

**Comment by DarktideLegend** [comment]
> you maybe able to use this as a base for this system. Dereth forever and an online DB connected content editor that did everything live..
> 
> https://gitlab.com/DerethForever/ContentEditor

Yeah just from briefly looking at the code, it will be a huge help. I won't use the server rendered views but I can use the Controllers for a REST API. The frontend I can build out separately.
